### ISSUE TITLE
I would LOVE to see this function 01

### ISSUE THREAD

**Issue by DoctorToBeIn23** [Arthur-Milchior/anki-number-of-selected-tags#2]
It would be great if you could have checkboxes you could select of which ones to make a filtered deck out of. I am willing to compensate you for your work as usual! 

![image](https://user-images.githubusercontent.com/60248099/79792612-6e347800-830c-11ea-897a-5b40ebafd0f8.png)

**Comment by DoctorToBeIn23** [comment]
Obviously it would create a filtered deck of the ones that you have selected as well as have the check box :)

**Comment by Farinata** [comment]
Hello, same here.
I would like for example to study **ALL** the cards from a deck that have a specific tag in them: for example "ENT" tag like I have explained here
[https://www.reddit.com/r/medicalschoolanki/comments/g4ycec/how_to_study_effectively_in_anking_by_tags/](url)

**Comment by AnKingMed** [comment]
Sounds like a really useful idea to me!

**Comment by Arthur-Milchior** [comment]
Would it always go to the same filtered deck (and so destroy the current selection)
Would it go to a new filtered deck and create a deck each time ?

**Comment by AnKingMed** [comment]
I would think a new filtered deck each time would be best

**Comment by DoctorToBeIn23** [comment]
Yeah new filtered deck each time would be ideal :)

**Comment by Arthur-Milchior** [comment]
Do you want to enter the name ? Or that it generates a name according to a pattern ? Such as 
Foo::Bar_random_number

**Comment by DoctorToBeIn23** [comment]
I think it would be nice to be able to name the deck yourself.

**Comment by Arthur-Milchior** [comment]
Please update and test. I spent two hours doing this feature and testing it (and let me tell you I hate how filtered decks are represented in the code. It makes no sens)

**Comment by DoctorToBeIn23** [comment]
Seems like the first column is supposed to just be check boxes but some of
them have what seems like is supposed to be a variation of the code
showing...?
[image: image.png]

>

**Comment by DoctorToBeIn23** [comment]
Looks likeits only showing up on the tags that got highlighted

**Comment by DoctorToBeIn23** [comment]
I also didnt see an option after checking some boxes to make a filtered
deck.

**Comment by Arthur-Milchior** [comment]
It's normal you didn't see the option. The first error broke the process. I believe the add-on never received the information that you clicked on some boxes.

Please update.

**Comment by DoctorToBeIn23** [comment]
1. The value I define for it to box istn working correct I put 75% and it
highlighted some that were in the 50's

2. Got this error when I check the box for the first time

Error
An error occurred. Please start Anki while holding down the shift key,
which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools >
Add-ons menu item to disable some add-ons and restart Anki, repeating until
you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please
report the issue on the add-on support site.
Debug info:
Anki 2.1.23 (de9543ff) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.15.4
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-04-25 10:06:58
Add-ons possibly involved: ⁨High Yield Tags⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 31, in cmd
  File "aqt/webview.py", line 97, in _onCmd
  File "aqt/webview.py", line 494, in _onBridgeCmd
  File "aqt/gui_hooks.py", line 1789, in __call__
  File "/Users/Jacob/Library/Application
Support/Anki2/addons21/1918380616/__init__.py", line 134, in select_tag
    (hyt, tag) = cmd.split(":")
ValueError: too many values to unpack (expected 2)

**Comment by Arthur-Milchior** [comment]
Oops, I didn't consider that you may have ":" in your tag... which is silly given the way your tag works. I'll correct it

**Comment by Arthur-Milchior** [comment]
The exception is corrected. It should work now

**Comment by Arthur-Milchior** [comment]
Is the problem 1. new ? Because I can't imagine how I did break that. I didn't change this part of the code

**Comment by Arthur-Milchior** [comment]
Which of the two options from the menu did you use ? Did you manually entered 75, or did you simply changed the value in the config ?
Is this a problem with both box and highlighting, or just with boxing ?

**Comment by DoctorToBeIn23** [comment]
1. I can now click the check boxes but still no luck with an option to then
make a filtered deck...
2. I changed it in the config, just box is an issue. It is highlighting
values below my set threshold

**Comment by DoctorToBeIn23** [comment]
Also the column names got shifted, see top of image
![image](https://user-images.githubusercontent.com/60248099/80313558-c950e980-87a8-11ea-839f-502e37224e62.png)

**Comment by Arthur-Milchior** [comment]
The shift should be corrected

**Comment by Arthur-Milchior** [comment]
Are you telling that, even if you check boxes, and close the window, you don't see any request for a deck name ? And that you don't see any error message either ?
Do you know how to start anki from a terminal, there may be error message printed there that could help me.

**Comment by Arthur-Milchior** [comment]
By any luck, would you have quote (double or single) in some tag ?

**Comment by Arthur-Milchior** [comment]
Please update and try again to create a deck

**Comment by DoctorToBeIn23** [comment]
As soon as I try and use the shortcut I got this error

Error
An error occurred. Please start Anki while holding down the shift key,
which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools >
Add-ons menu item to disable some add-ons and restart Anki, repeating until
you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please
report the issue on the add-on support site.
Debug info:
Anki 2.1.23 (de9543ff) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.15.4
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-04-26 10:26:08
Add-ons possibly involved: ⁨High Yield Tags⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/Jacob/Library/Application
Support/Anki2/addons21/1918380616/__init__.py", line 129, in <lambda>
    a.triggered.connect(lambda: showTagsInfoHighlight(
  File "/Users/Jacob/Library/Application
Support/Anki2/addons21/1918380616/__init__.py", line 26, in
showTagsInfoHighlight
    showTagsInfo(self, cids, highlights)
  File "/Users/Jacob/Library/Application
Support/Anki2/addons21/1918380616/__init__.py", line 32, in showTagsInfo
    info = tagStats(cids, highlights, highlights_percent)
  File "/Users/Jacob/Library/Application
Support/Anki2/addons21/1918380616/__init__.py", line 88, in tagStats
    nbCardWithThisTag = len(mw.col.findCards(search))
  File "anki/collection.py", line 630, in findCards
  File "anki/find.py", line 55, in findCards
Exception: invalidSearch

**Comment by DoctorToBeIn23** [comment]
I dont think I have any quotes in tags, I wasnt aware after checking the
boxes the filtered deck would be triggered when I closed the window.

**Comment by Arthur-Milchior** [comment]
I tried a correction; not sure it's going to be correct. Can you please try again

**Comment by DoctorToBeIn23** [comment]
The custom decks seems to be working, I am still having trouble getting the
box to only show up on the % I type in and or set in the config

**Comment by DoctorToBeIn23** [comment]
Example: I had the default set to 60% in the config
![image](https://user-images.githubusercontent.com/60248099/80320470-cc150400-87d3-11ea-9b9e-8541e6c5891a.png)

**Comment by DoctorToBeIn23** [comment]
I also notice when it makes the filtered deck I have to refresh the main screen with the decks and also manually rebuild it for the cards to show up. Not that big of a deal just thought you would like to know.

**Comment by Arthur-Milchior** [comment]
Deck is filled on construction (since you're not reviewing it, that's far easier to do in this case), and main window rebuild

**Comment by Arthur-Milchior** [comment]
Please update. I believe I have corrected the bug

**Comment by DoctorToBeIn23** [comment]
Seems to be working, let me test it out today and tomorrow to check for any
more bugs :)

**Comment by DoctorToBeIn23** [comment]
Hey Arthur everything seems to be working, how much time did you spend?

**Comment by Arthur-Milchior** [comment]
I believe I spent something like three quarter of hours more debugging. So 2h45 on this add-on
